### ISSUE TITLE
It's so cool!

### ISSUE THREAD

**Issue by WeDoX** [I2NhbmloZWxweW91/Styla#1]
It's so cool! How did you do it? Can you show me the code? I'm so sorry.

**Comment by hddananjaya** [comment]
@WeDox sorry couldn't find the source. This is really simple, I hold styled unicodes in arrays in order(a-z). Also I have the english alpabat in an array.
This is the pseudocode
```
for i in user_input_string
    index = get_index_of i from english_array 
    unicode_character = unicode_list1[index]
    replace i from unicode_character
```
if you really need the source reverse engineer the apk, I didn't obfuscate.

**Comment by WeDoX** [comment]
> @WeDox sorry couldn't find the source. This is really simple, I hold styled unicodes in arrays in order(a-z). Also I have the english alpabat in an array.
> This is the pseudocode
> 
> ```
> for i in user_input_string
>     index = get_index_of i from english_array 
>     unicode_character = unicode_list1[index]
>     replace i from unicode_character
> ```
> 
> if you really need the source reverse engineer the apk, I didn't obfuscate.

Thank you for the reply. I  want the source code just to confirm my guess.I now know it work.
